postgresql:
  image: "postgres:15"
  port: 5432
  storage:
    size: "5Gi"
    storageClass: "manual"  # Leave empty to use default storage class
  username: "admin"
  password: "adminpassword"
  database: "mydb"

flyway:
  image: "flyway/flyway:9.0"
  migrateCommand: ["migrate"]
  migrationDir: "/flyway/sql"
  initContainerImage: "busybox"
  sqlScripts:
    - "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(255));"
