apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
spec:
  template:
    spec:
      containers:
      - name: flyway
        {{ if .Values.job.image.tag }}
        image: "{{ .Values.job.image.name }}:{{ .Values.job.image.tag }}"
        {{ else }}
        image: "{{ .Values.job.image.name }}"
        {{ end }}
        imagePullPolicy: IfNotPresent
        args:
        - info
        - migrate
        - info
        {{- with .Values.job.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}