apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: {{ .Values.postgresql.storage.storageClass | default "" | quote }}
  capacity:
    storage: {{ .Values.postgresql.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"