apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: {{ .Values.volume.spec.storageClassName }}
  capacity:
    storage: {{ .Values.volume.spec.capacity.storage }}
  {{- with .Values.volume.spec.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostPath:
    path: {{ .Values.volume.spec.hostPath.path }}